export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const PRODUCT_DETAILS = 'PRODUCT_DETAILS';
